---
title: "First try in fitting a model"
output:
  github_document:
    toc: true
---


## Let's load the libraries

```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(rstan)
library(modelr)
library(rlang)
library(GGally)
library(tidybayes)            # install from github
library(tidybayes.rethinking) # install from github
library(gganimate)            # install from github
library(rethinking)
library(shinystan)


theme_set(theme_light())
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

## Let's create and normalize the dataframe

```{r}

d = read.csv('SliderBias-PctStudy.tsv', sep='\t') %>%
  mutate(expected_rating = expected_rating/100, rating = rating/100) %>% 
  filter(expected_rating!=0.0 & expected_rating!=1.0 & rating!=0.0 & rating!=1.0) %>% 
  sample_n(1000)

```

## Map user_number to values starting from 1

```{r}
unique_user_values = unique(d$user_number)
user_values = 1:length(unique_user_values)
names(user_values) <- unique_user_values

```

```{r}
user_values
```



```{r}
convert_user_number_to_counter <- function(user_number){
  as.integer(unlist(user_values[[toString(user_number)]]))
}
```



```{r}
typeof (convert_user_number_to_counter(4049))
```


```{r}
d$user_number <- sapply(d$user_number, convert_user_number_to_counter)
```



## Convert the data to the format stan needs

```{r}
standata = list(
  rating=d$rating,
  expected_rating=d$expected_rating,
  N=nrow(d)
)
```

## Fit the model

```{r}
fit <- stan(file = 'vas-model.stan', data = standata, 
            iter = 1000, chains = 4)
```

```{r}
y <- as.data.frame(fit) 
```

```{r}
pairs(y)
```
```{r}
show(fit)
```

```{r}
plot(fit)
```

```{r, eval = FALSE}
#launch_shinystan(fit)
```


## Simulate expected_ratings
```{r}

sim_df <-  seq(from=0, to=1, length.out=100) %>% 
    as.data.frame() %>% 
      subset(. != 0 & . != 1 ) %>% 
        plyr::rename(c("."="sim_exp_rating"))

```


## Calculate mu and merge 
```{r}

d_new = merge(y, sim_df, all = TRUE) %>% 
 mutate(mu  = inv_logit(a + b * logit(sim_exp_rating)), pred = rbeta(n(), (mu * v) , (1 - mu) * v))

```

## Try plotting

Aesthetics must be either length 1 or the same as the data (196000): y, x error comes when try to Knit the below code. 

```{r}

d_new %>% 
    ggplot(aes(x= sim_exp_rating))+
    stat_lineribbon(aes(y = pred-sim_exp_rating), .prob = c(.99, .9, .8, .5)) +
    geom_point(aes(y=rating-expected_rating, x = expected_rating), data = d, alpha=0.3) +
      
    scale_fill_brewer() +
      ggtitle("Test Plot")

```

# Multi-level modeling

```{r}
standata_ml = list(
  rating=d$rating,
  expected_rating=d$expected_rating,
  user_number = d$user_number,
  N=nrow(d),
  k=max(d$user_number)
)
```


```{r}
fit_ml <- stan(file = 'vas-model-multilevel.stan', data = standata_ml, 
            iter = 1000, chains = 4, control=list(adapt_delta=0.9))
```

```{r}
y_ml <- as.data.frame(fit_ml) 
```


